default_platform(:ios)

platform :ios do
  desc "Sync development signing"
  lane :sync_dev_signing do |options|
    match(
      type: "development",
      git_url: "git@github.com:Codetector1374/apple_developer_certs.git",
      readonly: options.fetch(:readonly, true),
      force_for_new_devices: options.fetch(:force_for_new_devices, false),
      include_all_certificates: options.fetch(:include_all_certificates, false),
      force_for_new_certificates: options.fetch(:force_for_new_certificates, false)
    )
  end

  desc "Sync App Store production signing"
  lane :sync_appstore_signing do |options|
    match(
      type: "appstore",
      git_url: "git@github.com:Codetector1374/apple_developer_certs.git",
      readonly: options.fetch(:readonly, true),
      force: options.fetch(:force, false)
    )
  end

  desc "Build CI App"
  lane :ci_build_ipa do
    keychain_name = "wetty-chat-ios-ci-#{ENV.fetch('BUILD_NUMBER', Time.now.to_i.to_s)}"

    begin
      setup_ci(
        force: true,
        keychain_name: keychain_name,
        timeout: 3600
      )

      sync_appstore_signing(readonly: true)

      Dir.chdir("..") do
        sh("flutter pub get")
        sh(
          "flutter build ipa " \
          "--release " \
          "--build-number #{ENV.fetch('FLUTTER_BUILD_NUMBER')} " \
          "--export-options-plist=ios/ExportOptions-AppStore.plist"
        )
      end
    ensure
      delete_keychain(name: keychain_name)
    end
  end
end
