export const STICKER_AUTO_SORT_LIMIT = 20;
export const MAX_REACTIONS_PER_USER_PER_MESSAGE = 5;
export const MAX_REACTION_HEAD_TABS = 8;
export const MAX_DISTINCT_REACTIONS_PER_MESSAGE = 50;
export const MAX_PINNED_REACTIONS = 5;
