when:
  - event: push
    branch:
      - main
      - woodpecker
    path:
      include:
        - backend/docker/Dockerfile.builder-base
        - backend/docker/Dockerfile.runtime-base
        - .woodpecker/backend-base-image.yaml
      on_empty: false

variables:
  - builder_repo: &builder_repo ghcr.io/chahua-im/chahua-backend-builder-base
  - runtime_repo: &runtime_repo ghcr.io/chahua-im/chahua-backend-runtime-base

steps:
  - name: publish builder base amd64
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      repo: *builder_repo
      registry: ghcr.io
      dockerfile: backend/docker/Dockerfile.builder-base
      context: backend
      platforms: linux/amd64
      provenance: false
      tags:
        - amd64-rust-1.95.0-trixie
      build_args:
        TARGETARCH: amd64
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token

  - name: publish builder base arm64
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      repo: *builder_repo
      registry: ghcr.io
      dockerfile: backend/docker/Dockerfile.builder-base
      context: backend
      platforms: linux/amd64
      provenance: false
      tags:
        - arm64-rust-1.95.0-trixie
      build_args:
        TARGETARCH: arm64
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token

  - name: publish runtime base
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      repo: *runtime_repo
      registry: ghcr.io
      dockerfile: backend/docker/Dockerfile.runtime-base
      context: backend
      platforms: linux/amd64,linux/arm64
      provenance: false
      tags:
        - trixie
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
