when:
  - event: pull_request
    branch:
      - main
      - woodpecker
  - event: push
    branch:
      - main
      - woodpecker

steps:
  - name: required checks
    image: alpine:3.20
    commands:
      - echo "All applicable checks passed"

depends_on:
  - name: frontend-check
    optional: true
  - name: backend-check
    optional: true
  - name: backend-base-image
    optional: true
